on: [push, pull_request]
jobs:
  Build-Docker-Image:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@v2
    - name: Cache terminology files
      uses: actions/cache@v2
      with:
        path: ~/terminology
        key: terminology-${{ github.sha }}
        restore-keys: terminology-
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Cache Docker layers
      uses: actions/cache@v2
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-
    - name: Docker Buildx
      run: |
        docker buildx build \
          --cache-from "type=local,src=/tmp/.buildx-cache" \
          --cache-to "type=local,dest=/tmp/.buildx-cache-new" \
          --tag fhirserver \
          .
    - name: Prepare ini file
      env:
        FHIRSERVER_LOCATIONS_CLONE_PATH: /work/fhirserver
        FHIRSERVER_LOCATIONS_TEST_CASES_CLONE_PATH: /work/bootstrap/source/fhir-test-cases
        FHIRSERVER_LOCATIONS_MARKDOWN_CLONE_PATH: /work/bootstrap/source/delphi-markdown
        FHIRSERVER_LOCATIONS_SNOMED_CACHE_PATH: /terminology/fhir-server/snomed.test.cache
        FHIRSERVER_EMAIL_SENDER: fhirservertests@gmail.com
        FHIRSERVER_EMAIL_DESTINATION: fhirservertests@gmail.com
        FHIRSERVER_EMAIL_PASSWORD: ${{ secrets.FHIRSERVER_EMAIL_PASSWORD }}
        FHIRSERVER_SSL_CERT_PATH: /work/fhirserver/fixtures/domain.crt
        FHIRSERVER_SSL_KEY_PATH: /work/fhirserver/fixtures/domain.key
        FHIRSERVER_SSL_CACERT_PATH: /work/fhiserver/fixtures/rootCA.crt
        FHIRSERVER_SSL_PASSWORD: password
      run: |
        cat fixtures/test-settings.ini.template | envsubst > ~/test-settings.ini
    - name: Ensure SNOMED cache is present
      run: |
        mkdir -p ~/terminology/fhir-server
        wget -q --no-clobber https://storage.googleapis.com/ig-build/snomed.test.cache -O ~/terminology/fhir-server/snomed.test.cache || true
        ls  ~/terminology/fhir-server/snomed.test.cache
    - name: Run tests in docker
      run: |
        docker run -v ~/terminology:/terminology -v ~/test-settings.ini:/work/fhirserver/exec/64/test-settings.ini fhirserver -tests
    - name: Update cache
      run: |
        rm -rf /tmp/.buildx-cache
        mv /tmp/.buildx-cache-new /tmp/.buildx-cache
